-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'EMPLOYEE',
ALTER COLUMN "locationId" DROP NOT NULL,
ALTER COLUMN "hourlyRate" DROP NOT NULL,
ALTER COLUMN "overtimeRate" DROP NOT NULL;
